language: cpp
sudo: required
dist: trusty
os:
  - osx
#env:
# - BUILD_CMAKE=yes
# - BUILD_CMAKE=yes CMAKE_OPTS="-DBUILD_wireshark_gtk=ON"
# - BUILD_CMAKE=yes CMAKE_OPTS="-DENABLE_PCAP=OFF"
# - BUILD_CMAKE=yes CMAKE_OPTS="-DENABLE_EXTCAP=OFF"
# - BUILD_CMAKE=no AUTOTOOLS_OPTS="--with-gtk=3"
before_install:
  - echo $TRAVIS_OS_NAME
  - $CC --version
  - flex -V
  # macos
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./tools/macos-setup-brew.sh; fi
  - flex -V
before_script:
  mkdir build && cd build && cmake -DENABLE_EXTRA_COMPILER_WARNINGS=1 .. 
script:
  - make
